services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '5000:80'
    networks:
      - dokploy-network

  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    ports:
      - '8000:8000'
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
